### ISSUE TITLE
Missing step in "Create your own"

### ISSUE THREAD

**Issue by joelthomastr** [MichaelCurrin/jekyll-gh-actions-quickstart#2]
Hi there, this is fantastic!

One little thing that took me 20 minutes to work out: In the "Create your own" page, maybe add a step between 1 and 2 to update lines 8 and 9 in the _config.yml file with the person's own github repo details. 

An added bonus is that this triggers the GH Pages Deploy, which I was trying to trigger using other methods.

**Comment by MichaelCurrin** [comment]
Thanks for the feedback.

How is this now?

https://github.com/MichaelCurrin/jekyll-gh-actions-quickstart/blob/main/create-your-own.md#deploy-from-template

**Comment by joelthomastr** [comment]
Yep! noice
